import AxeBuilder from '@axe-core/playwright'
import { test, expect, control, signIn } from './fixtures'

test('real report editorial preserves drafts, pins approval and publishes only after review', async ({ page, request, identity }, info) => {
  const report = await control(request, 'editorial-report', { ownerId: identity.id })
  await signIn(page, identity)
  await page.goto(`/reporting/${report.id}`)
  const editorial = page.getByRole('region', { name: 'Report review and publication', exact: true })
  await expect(editorial.getByRole('heading')).toContainText('draft')
  expect(await control(request, `editorial-deliveries/${report.id}`)).toEqual({ count: 0 })
  await editorial.getByRole('button', { name: 'Edit draft', exact: true }).click()
  await editorial.getByLabel('Report title', { exact: true }).fill('Reviewed browser publication')
  await editorial.getByLabel('Executive Summary Markdown', { exact: true }).fill('Reviewed claim: twelve affected systems [S1].')
  await page.getByRole('button', { name: '← Report library', exact: true }).click()
  const discard = page.getByRole('alertdialog', { name: 'Discard unsaved changes?', exact: true })
  await expect(discard).toBeVisible()
  await discard.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(editorial.getByLabel('Report title', { exact: true })).toHaveValue('Reviewed browser publication')
  const saved = page.waitForResponse((response) => response.url().endsWith(`/reports/${report.id}/draft`) && response.request().method() === 'PUT')
  await editorial.getByRole('button', { name: 'Save draft', exact: true }).click()
  expect((await saved).status()).toBe(200)
  await expect(editorial.getByRole('button', { name: 'Edit draft', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Reviewed browser publication', exact: true })).toBeVisible()
  await editorial.getByLabel('Review note (optional)', { exact: true }).fill('Checked against the retained source.')
  await editorial.getByRole('button', { name: 'Submit for review', exact: true }).click()
  await expect(editorial.getByRole('button', { name: 'Approve this revision', exact: true })).toBeEnabled()
  await page.reload()
  await expect(editorial).toContainText('Checked against the retained source.')
  await editorial.getByRole('button', { name: 'Approve this revision', exact: true }).click()
  await expect(editorial).toContainText('Author self-review')
  expect(await control(request, `editorial-deliveries/${report.id}`)).toEqual({ count: 0 })
  // A return to draft invalidates approval; publishing cannot skip another review.
  await editorial.getByRole('button', { name: 'Return to draft', exact: true }).click()
  await expect(editorial.getByRole('button', { name: 'Submit for review', exact: true })).toBeEnabled()
  await expect(editorial.getByRole('button', { name: 'Publish approved revision', exact: true })).toHaveCount(0)
  await editorial.getByRole('button', { name: 'Submit for review', exact: true }).click()
  await editorial.getByRole('button', { name: 'Approve this revision', exact: true }).click()
  await editorial.getByRole('button', { name: 'Publish approved revision', exact: true }).click()
  await expect(editorial).toContainText('Published content is immutable.')
  await expect(editorial.getByRole('button', { name: 'Edit draft', exact: true })).toHaveCount(0)
  expect(await control(request, `editorial-deliveries/${report.id}`)).toEqual({ count: 1 })
  const response = await page.request.get(`/api/v1/reports/${report.id}`)
  expect(response.status()).toBe(200)
  const persisted = await response.json()
  expect(persisted).toMatchObject({ publication_status: 'published', approval_self_review: true, revision_current: true, title: 'Reviewed browser publication' })
  expect(persisted.sections[0].body_markdown).toBe('Reviewed claim: twelve affected systems [S1].')
  await page.reload()
  await expect(editorial).toContainText('Published content is immutable.')
  const accessibility = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa', 'wcag22aa']).analyze()
  await info.attach('axe-published-report-editorial', { body: JSON.stringify(accessibility, null, 2), contentType: 'application/json' })
  expect(accessibility.violations.map(({ id, nodes }) => ({ id, targets: nodes.map((node) => node.target) }))).toEqual([])
})
