#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: ./bootstrap.sh [--force] [output-file]
       ./bootstrap.sh --print-portainer-env

Generate a local .env file with fresh random secrets for the default
Docker Compose stack. The default output file is .env in the current directory.

Use --print-portainer-env to print a complete Portainer stack environment
block instead of writing a file.

Environment overrides:
  ADMIN_EMAIL      Admin email to write into the generated output.
  ADMIN_PASSWORD   Admin password to write into the generated output.
USAGE
}

force=false
output_file=""
print_portainer_env=false

while [ "$#" -gt 0 ]; do
  case "$1" in
    --force)
      force=true
      shift
      ;;
    --print-portainer-env)
      print_portainer_env=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      if [ -n "$output_file" ]; then
        echo "Unexpected argument: $1" >&2
        usage >&2
        exit 2
      fi
      output_file="$1"
      shift
      ;;
  esac
done

if [ "$print_portainer_env" = "true" ] && [ -n "$output_file" ]; then
  echo "--print-portainer-env does not take an output file." >&2
  usage >&2
  exit 2
fi

if [ "$print_portainer_env" = "true" ] && [ "$force" = "true" ]; then
  echo "--force is only used when writing a local .env file." >&2
  usage >&2
  exit 2
fi

if [ -z "$output_file" ] && [ "$print_portainer_env" != "true" ]; then
  output_file=".env"
fi

if [ -n "$output_file" ] && [ -e "$output_file" ] && [ "$force" != "true" ]; then
  echo "$output_file already exists. Use --force to replace it." >&2
  exit 1
fi

random_value() {
  local length="${1:-48}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 "$length" | tr '+/' '-_' | tr -d '=\n' | cut -c "1-$length"
    return
  fi

  if command -v python3 >/dev/null 2>&1; then
    python3 - "$length" <<'PY'
import secrets
import sys

length = int(sys.argv[1])
print(secrets.token_urlsafe(length)[:length])
PY
    return
  fi

  echo "Unable to generate secrets: install openssl or python3." >&2
  exit 1
}

postgres_password="$(random_value 40)"
redis_password="$(random_value 40)"
jwt_secret="$(random_value 64)"
app_data_encryption_key="$(random_value 64)"
admin_email="${ADMIN_EMAIL:-admin@example.com}"
admin_password="${ADMIN_PASSWORD:-$(random_value 24)}"
compose_project_name="${COMPOSE_PROJECT_NAME:-$(basename "$PWD" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_-]//g')}"
if [ -z "$compose_project_name" ]; then
  compose_project_name="threatlens"
fi
postgres_volume_name="${compose_project_name}_postgres_data"

render_env_block() {
  cat <<EOF
POSTGRES_DB=threatlens
POSTGRES_USER=threatlens
POSTGRES_PASSWORD=$postgres_password
REDIS_PASSWORD=$redis_password
DATABASE_URL=
REDIS_URL=
JWT_SECRET=$jwt_secret
APP_DATA_ENCRYPTION_KEY=$app_data_encryption_key
APP_DATA_ENCRYPTION_PREVIOUS_KEYS=
REQUIRE_EXPLICIT_DATA_ENCRYPTION_KEY=true
JWT_EXPIRES_MINUTES=1440
ADMIN_EMAIL=$admin_email
ADMIN_PASSWORD=$admin_password
SEED_ADMIN_ON_STARTUP=true
SEED_ADMIN_FORCE_ROLE=false
SEED_ADMIN_REACTIVATE_EXISTING=false
SEED_ADMIN_RESET_PASSWORD_ON_STARTUP=false
APP_ENV=development
AUTH_COOKIE_SECURE=false
AUTH_COOKIE_SAMESITE=lax
AUTH_REQUIRE_CSRF=true
AUTH_COOKIE_NAME=threatlens_session
AUTH_CSRF_COOKIE_NAME=threatlens_csrf
AUTH_CSRF_HEADER_NAME=x-csrf-token
RUN_MIGRATIONS_ON_STARTUP=true
ALLOW_SELF_REGISTRATION=false
ALLOW_LEGACY_UNSCOPED_TOKENS=false
AI_ENABLED=false
AI_API_KEY=
ALLOW_PRIVATE_NETWORK_FETCH=false
ALLOW_PRIVATE_NETWORK_AI=false
ALLOW_PRIVATE_NETWORK_WEBHOOKS=false
NOTIFICATION_WEBHOOK_ALLOWED_HOSTS=
NOTIFICATION_WEBHOOK_ALLOW_ADMIN_UNRESTRICTED=false
WEB_VITE_API_BASE_URL=/api/v1
THREATLENS_WEB_PORT=3000
THREATLENS_CSP_CONNECT_SRC="'self'"
THREATLENS_CSP_FRAME_SRC="'self'"
LOG_LEVEL=INFO
EOF
}

if [ "$print_portainer_env" = "true" ]; then
  render_env_block
  exit 0
fi

umask 077
cat > "$output_file" <<EOF
# Generated by bootstrap.sh.
# These values are intended for a local HTTP deployment at http://localhost:3000.
# Review .env.example before using this file for an internet-facing deployment.
$(render_env_block)
EOF
chmod 600 "$output_file"

cat <<EOF
Created $output_file

Admin login:
  Email:    $admin_email
  Password: $admin_password

Start ThreatLens with:
  docker compose pull
  docker compose up -d

After the first admin account exists, you can set SEED_ADMIN_ON_STARTUP=false in $output_file.
EOF

if command -v docker >/dev/null 2>&1 && docker volume inspect "$postgres_volume_name" >/dev/null 2>&1; then
  cat <<EOF

Warning: Docker volume $postgres_volume_name already exists.
If this is from a failed first startup and the API logs say the PostgreSQL role
"threatlens" does not exist, reset the local database volume with:
  docker compose down -v
  docker compose up -d
EOF
fi
