#!/usr/bin/env python3
"""Generate runtime dependency inventories for release artifacts.

Backend inventory is generated from the currently running Python environment.
For release artifacts, run this script inside the built backend image so the
output matches the redistributed runtime stack from backend/Dockerfile.

Frontend inventory is generated from web/package-lock.json and includes only
runtime packages (entries where package-lock marks "dev" as false or absent).
"""

from __future__ import annotations

import argparse
import importlib.metadata as metadata
import json
from pathlib import Path


def _sorted_backend_distributions() -> list[str]:
    rows: dict[str, str] = {}
    for dist in metadata.distributions():
        name = (dist.metadata.get("Name") or "").strip()
        version = (dist.version or "").strip()
        if not name or not version:
            continue
        key = name.lower().replace("_", "-")
        rows[key] = f"{name}=={version}"
    return [rows[key] for key in sorted(rows)]


def _sorted_frontend_packages(lockfile_path: Path) -> list[str]:
    data = json.loads(lockfile_path.read_text())
    packages = data.get("packages", {})
    rows: dict[str, str] = {}
    for package_path, package_meta in packages.items():
        if not package_path.startswith("node_modules/"):
            continue
        if package_meta.get("dev"):
            continue
        name = (package_meta.get("name") or package_path.split("node_modules/", 1)[1]).strip()
        version = (package_meta.get("version") or "").strip()
        if not name or not version:
            continue
        rows[name.lower()] = f"{name}=={version}"
    return [rows[key] for key in sorted(rows)]


def _write_inventory(path: Path, header: str, lines: list[str]) -> None:
    content = "\n".join(
        [
            header,
            "# Generated by backend/scripts/generate_dependency_inventory.py",
            "",
            *lines,
            "",
        ]
    )
    path.write_text(content)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--backend-output", type=Path, help="Path for the resolved backend runtime inventory.")
    parser.add_argument(
        "--frontend-output",
        type=Path,
        help="Path for the resolved frontend runtime inventory.",
    )
    parser.add_argument(
        "--frontend-lockfile",
        type=Path,
        default=Path("web/package-lock.json"),
        help="Path to the frontend package-lock.json file.",
    )
    parser.add_argument(
        "--skip-backend",
        action="store_true",
        help="Skip backend inventory generation even if --backend-output is provided.",
    )
    parser.add_argument(
        "--skip-frontend",
        action="store_true",
        help="Skip frontend inventory generation even if --frontend-output is provided.",
    )
    args = parser.parse_args()

    if args.backend_output and not args.skip_backend:
        args.backend_output.parent.mkdir(parents=True, exist_ok=True)
        _write_inventory(
            args.backend_output,
            "# ThreatLens backend runtime dependency inventory",
            _sorted_backend_distributions(),
        )

    if args.frontend_output and not args.skip_frontend:
        args.frontend_output.parent.mkdir(parents=True, exist_ok=True)
        _write_inventory(
            args.frontend_output,
            "# ThreatLens frontend runtime dependency inventory",
            _sorted_frontend_packages(args.frontend_lockfile),
        )

    if (not args.backend_output or args.skip_backend) and (not args.frontend_output or args.skip_frontend):
        parser.error("No output requested. Provide --backend-output and/or --frontend-output.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
