import type { ReportDetail } from '../src/types/api'

export const reportMarkdown = [
  '## Operational assessment',
  '',
  '**Critical** activity needs *careful validation* against [S1].',
  '',
  '### Priorities',
  '',
  '1. Investigate the exposed service.',
  '   - Confirm the affected version [S1].',
  '   - Review `service --status` before changes.',
  '2. Record the outcome.',
  '',
  '| Signal | Action | Evidence |',
  '| --- | --- | --- |',
  '| **Exposure** | Validate patch level | [S1] |',
  '| Unknown | ~~Dismiss~~ Investigate | [S99] |',
  '',
  '> Verify the evidence before containment.',
  '',
  '```sh',
  'printf "[S1] <script>example</script>"',
  '```',
  '',
  '[Read advisory](https://advisory.example.test/details)',
  '',
  '![Untrusted chart](https://tracking.example.test/chart.png)',
  '',
  '<script>window.reportInjected = true</script>',
  '<img src="https://tracking.example.test/raw.png" onerror="window.reportInjected=true">',
  '',
  '[Unsafe link](javascript:alert%281%29) and [Encoded link](jav&#x61;script:alert%281%29).',
].join('\n')

export function markdownReport(): ReportDetail {
  return {
    id: 'markdown-report', title: 'Threat assessment', owner_user_id: 'browser-analyst',
    template_id: null, schedule_id: null, report_type: 'custom', status: 'ready', trigger_source: 'manual',
    generation_stage: 'ready', period_start: '2026-09-01T00:00:00Z', period_end: '2026-09-08T00:00:00Z',
    source_count: 1, included_source_count: 1, model_calls: 1, provider: 'fixture', model: 'fixture',
    error_code: null, error: null, generated_at: '2026-09-08T10:00:00Z', created_at: '2026-09-08T09:00:00Z',
    filters: { q: null, feed_ids: [], tag_ids: [], tags_mode: 'any', classifications: [], ai_relevance_labels: [],
      ai_score_min: null, ai_score_max: null, is_read: null, is_starred: null, has_article_text: null,
      since: null, until: null, date_basis: 'published_at_or_first_seen_at', sort: 'published_at_desc' },
    prompt: { audience: 'security_team', objective: 'Assess threats.', tone: 'analytical', detail_level: 'standard',
      use_company_context: false, custom_instructions: null, focus_topics: [], excluded_topics: [] },
    sections_config: [{ key: 'assessment', title: 'Assessment', enabled: true }], metrics: {},
    coverage: { coverage_percent: 100, warnings: [] }, summary_text: 'Assess current threats.',
    estimated_input_tokens: 100, prompt_tokens: 100, completion_tokens: 200, total_tokens: 300,
    context_window_tokens: 8192, generation_batches: 1, delivery_requested: false, delivery_mode: 'summary',
    sections: [{ key: 'assessment', title: 'Assessment', position: 0, status: 'ready', body_markdown: reportMarkdown,
      key_points: [], citations: ['S1'], error: null }],
    sources: [{ citation_key: 'S1', item_id: 'item-1', included: true, rank: 1, exclusion_reason: null,
      title: 'Verified advisory', feed_name: 'CERT fixture', url: 'https://evidence.example.test/advisory',
      classification: 'vulnerability', relevance_score: 0.9, relevance_label: 'high', published_at: null,
      first_seen_at: '2026-09-08T00:00:00Z', tags: [], iocs: [], estimated_tokens: 100 }],
  }
}
